#!/bin/bash
#SBATCH -n 4 # Number of cores
#SBATCH --mem 1000 # 2GB solicitados.
#SBATCH -p mhigh,mhigh # or mlow Partition to submit to master low prioriy queue
#SBATCH --gres gpu:1 # Para pedir Pascales MAX 8
#SBATCH -o %x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e %x_%u_%j.err # File to which STDERR will be written
eval "$(conda shell.bash hook)"
conda activate m6
# commanda terminal --> sbatch --gres gpu:1 -n 10 job
python main.py --run_mode AdaptiveGaussian --run_name task1 -a 3 4 5 6 7 -p 0.25 --rho 0.025 0.05 0.075 0.1 -c gray 
