#!/bin/bash
#SBATCH -n 10 # Number of cores
#SBATCH --mem 60GB # 2GB solicitados.
#SBATCH -p mhigh,mhigh # or mlow Partition to submit to master low prioriy queue
#SBATCH --gres gpu:1 # Para pedir Pascales MAX 8
#SBATCH -o %x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e %x_%u_%j.err # File to which STDERR will be written
eval "$(conda shell.bash hook)"
conda activate m6

echo "Starting TrackEval for EndToEnd MTSC"

echo "BY TRACK S03"
python TrackEval_ourMethods.py --evaluated 0 
python /ghome/group03/mcv-m6-2023-team6/week5/TrackEval/S03/scripts/run_mot_challenge.py --DO_PREPROC False --METRICS HOTA Identity
python TrackEval_ourMethods.py --evaluated 1
